apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app-room-playback
  name: app-room-playback
  namespace: common-ucs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-room-playback
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        # io.kompose.network/ionnet: "true"
        io.kompose.service: app-room-playback
    spec:
      containers:
        - image: app-room-playback:main-406a1d4
          name: app-room-playback
          resources: {}
          volumeMounts:
            - mountPath: /configs/app-room-playback.toml
              name: app-room-playback-claim0
              subPath: app-room-playback.toml
      restartPolicy: Always
      volumes:
        - name: app-room-playback-claim0
          configMap:
            name: app-room-playback-config
status: {}